
#No problem with passwords here as they are just for test databases
test_environment:
    TEST1_TABLE_NAME: "test_table"

firebird:
    DATABASE_PATH: "test_firebird.fdb"
    DATABASE_HOST: "localhost"

mysql:
    DATABASE_PATH: "test_mysql"
    DATABASE_HOST: "localhost"

postgres:
    DATABASE_PATH: "test_postgres"
    DATABASE_HOST: "localhost"
